import type { Metadata } from "next";
import "./globals.css";
import "@/app/styles/global.scss";
import React from "react";
import Footer from "./components/layouts/footer";
import Header from "./components/layouts/header";

export const metadata: Metadata = {
  title: "Clothes smart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main style={{ paddingTop: "132px" }}> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
